// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectOAuthToAccount = `-- name: ConnectOAuthToAccount :one
UPDATE instagram_accounts SET
    ig_user_id = $2,
    ig_username = $3,
    access_token = $4,
    token_expires_at = $5,
    profile_pic_url = $6,
    is_oauth_connected = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at
`

type ConnectOAuthToAccountParams struct {
	ID             uuid.UUID  `json:"id"`
	IgUserID       *string    `json:"ig_user_id"`
	IgUsername     string     `json:"ig_username"`
	AccessToken    *string    `json:"access_token"`
	TokenExpiresAt *time.Time `json:"token_expires_at"`
	ProfilePicUrl  *string    `json:"profile_pic_url"`
}

func (q *Queries) ConnectOAuthToAccount(ctx context.Context, arg ConnectOAuthToAccountParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, connectOAuthToAccount,
		arg.ID,
		arg.IgUserID,
		arg.IgUsername,
		arg.AccessToken,
		arg.TokenExpiresAt,
		arg.ProfilePicUrl,
	)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgUsername,
		&i.IgUserID,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.ProfilePicUrl,
		&i.FollowersCount,
		&i.IsOauthConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO instagram_accounts (user_id, ig_username, is_oauth_connected)
VALUES ($1, $2, FALSE)
RETURNING id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at
`

type CreateAccountParams struct {
	UserID     uuid.UUID `json:"user_id"`
	IgUsername string    `json:"ig_username"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.IgUsername)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgUsername,
		&i.IgUserID,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.ProfilePicUrl,
		&i.FollowersCount,
		&i.IsOauthConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO instagram_accounts (user_id, ig_username, ig_user_id, access_token, token_expires_at, is_oauth_connected)
VALUES ($1, $2, $3, $4, $5, TRUE)
RETURNING id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID         uuid.UUID  `json:"user_id"`
	IgUsername     string     `json:"ig_username"`
	IgUserID       *string    `json:"ig_user_id"`
	AccessToken    *string    `json:"access_token"`
	TokenExpiresAt *time.Time `json:"token_expires_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.IgUsername,
		arg.IgUserID,
		arg.AccessToken,
		arg.TokenExpiresAt,
	)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgUsername,
		&i.IgUserID,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.ProfilePicUrl,
		&i.FollowersCount,
		&i.IsOauthConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM instagram_accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at FROM instagram_accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgUsername,
		&i.IgUserID,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.ProfilePicUrl,
		&i.FollowersCount,
		&i.IsOauthConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at FROM instagram_accounts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]InstagramAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstagramAccount{}
	for rows.Next() {
		var i InstagramAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IgUsername,
			&i.IgUserID,
			&i.AccessToken,
			&i.TokenExpiresAt,
			&i.ProfilePicUrl,
			&i.FollowersCount,
			&i.IsOauthConnected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsWithExpiringTokens = `-- name: GetAccountsWithExpiringTokens :many
SELECT id, user_id, ig_username, ig_user_id, access_token, token_expires_at, profile_pic_url, followers_count, is_oauth_connected, created_at, updated_at FROM instagram_accounts
WHERE is_oauth_connected = TRUE
  AND token_expires_at < NOW() + INTERVAL '7 days'
  AND access_token IS NOT NULL
`

func (q *Queries) GetAccountsWithExpiringTokens(ctx context.Context) ([]InstagramAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsWithExpiringTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstagramAccount{}
	for rows.Next() {
		var i InstagramAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IgUsername,
			&i.IgUserID,
			&i.AccessToken,
			&i.TokenExpiresAt,
			&i.ProfilePicUrl,
			&i.FollowersCount,
			&i.IsOauthConnected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountProfile = `-- name: UpdateAccountProfile :exec
UPDATE instagram_accounts SET
    profile_pic_url = $2,
    followers_count = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccountProfileParams struct {
	ID             uuid.UUID `json:"id"`
	ProfilePicUrl  *string   `json:"profile_pic_url"`
	FollowersCount *int32    `json:"followers_count"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) error {
	_, err := q.db.Exec(ctx, updateAccountProfile, arg.ID, arg.ProfilePicUrl, arg.FollowersCount)
	return err
}

const updateAccountToken = `-- name: UpdateAccountToken :exec
UPDATE instagram_accounts SET
    access_token = $2,
    token_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccountTokenParams struct {
	ID             uuid.UUID  `json:"id"`
	AccessToken    *string    `json:"access_token"`
	TokenExpiresAt *time.Time `json:"token_expires_at"`
}

func (q *Queries) UpdateAccountToken(ctx context.Context, arg UpdateAccountTokenParams) error {
	_, err := q.db.Exec(ctx, updateAccountToken, arg.ID, arg.AccessToken, arg.TokenExpiresAt)
	return err
}
