// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brand_dna.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBrandDna = `-- name: CreateBrandDna :one
INSERT INTO brand_dna (
    instagram_account_id, score, tone, visual_style,
    strong_topics, weak_areas, best_formats, best_posting_times,
    avg_posting_frequency, hashtag_strategy,
    strengths, recommendations, raw_analysis
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, instagram_account_id, score, tone, visual_style, strong_topics, weak_areas, best_formats, best_posting_times, avg_posting_frequency, hashtag_strategy, strengths, recommendations, raw_analysis, created_at
`

type CreateBrandDnaParams struct {
	InstagramAccountID  uuid.UUID       `json:"instagram_account_id"`
	Score               int32           `json:"score"`
	Tone                string          `json:"tone"`
	VisualStyle         *string         `json:"visual_style"`
	StrongTopics        []string        `json:"strong_topics"`
	WeakAreas           []string        `json:"weak_areas"`
	BestFormats         []string        `json:"best_formats"`
	BestPostingTimes    []string        `json:"best_posting_times"`
	AvgPostingFrequency *string         `json:"avg_posting_frequency"`
	HashtagStrategy     *string         `json:"hashtag_strategy"`
	Strengths           json.RawMessage `json:"strengths"`
	Recommendations     json.RawMessage `json:"recommendations"`
	RawAnalysis         []byte          `json:"raw_analysis"`
}

func (q *Queries) CreateBrandDna(ctx context.Context, arg CreateBrandDnaParams) (BrandDna, error) {
	row := q.db.QueryRow(ctx, createBrandDna,
		arg.InstagramAccountID,
		arg.Score,
		arg.Tone,
		arg.VisualStyle,
		arg.StrongTopics,
		arg.WeakAreas,
		arg.BestFormats,
		arg.BestPostingTimes,
		arg.AvgPostingFrequency,
		arg.HashtagStrategy,
		arg.Strengths,
		arg.Recommendations,
		arg.RawAnalysis,
	)
	var i BrandDna
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Score,
		&i.Tone,
		&i.VisualStyle,
		&i.StrongTopics,
		&i.WeakAreas,
		&i.BestFormats,
		&i.BestPostingTimes,
		&i.AvgPostingFrequency,
		&i.HashtagStrategy,
		&i.Strengths,
		&i.Recommendations,
		&i.RawAnalysis,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBrandDna = `-- name: GetLatestBrandDna :one
SELECT id, instagram_account_id, score, tone, visual_style, strong_topics, weak_areas, best_formats, best_posting_times, avg_posting_frequency, hashtag_strategy, strengths, recommendations, raw_analysis, created_at FROM brand_dna
WHERE instagram_account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBrandDna(ctx context.Context, instagramAccountID uuid.UUID) (BrandDna, error) {
	row := q.db.QueryRow(ctx, getLatestBrandDna, instagramAccountID)
	var i BrandDna
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Score,
		&i.Tone,
		&i.VisualStyle,
		&i.StrongTopics,
		&i.WeakAreas,
		&i.BestFormats,
		&i.BestPostingTimes,
		&i.AvgPostingFrequency,
		&i.HashtagStrategy,
		&i.Strengths,
		&i.Recommendations,
		&i.RawAnalysis,
		&i.CreatedAt,
	)
	return i, err
}
