// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brand_settings.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getBrandSettings = `-- name: GetBrandSettings :one
SELECT id, instagram_account_id, content_goal, tone_traits, tone_custom_note, mix_useful, mix_selling, mix_personal, mix_entertaining, format_reels_enabled, format_reels_pct, format_carousel_enabled, format_carousel_pct, format_photo_enabled, format_photo_pct, banned_topics, banned_words, competitor_names, content_restrictions, custom_rules, products_services, target_audience, usp, team_members, location_address, working_hours, upcoming_events, content_language, posting_frequency, niche, created_at, updated_at FROM brand_settings WHERE instagram_account_id = $1
`

func (q *Queries) GetBrandSettings(ctx context.Context, instagramAccountID uuid.UUID) (BrandSetting, error) {
	row := q.db.QueryRow(ctx, getBrandSettings, instagramAccountID)
	var i BrandSetting
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.ContentGoal,
		&i.ToneTraits,
		&i.ToneCustomNote,
		&i.MixUseful,
		&i.MixSelling,
		&i.MixPersonal,
		&i.MixEntertaining,
		&i.FormatReelsEnabled,
		&i.FormatReelsPct,
		&i.FormatCarouselEnabled,
		&i.FormatCarouselPct,
		&i.FormatPhotoEnabled,
		&i.FormatPhotoPct,
		&i.BannedTopics,
		&i.BannedWords,
		&i.CompetitorNames,
		&i.ContentRestrictions,
		&i.CustomRules,
		&i.ProductsServices,
		&i.TargetAudience,
		&i.Usp,
		&i.TeamMembers,
		&i.LocationAddress,
		&i.WorkingHours,
		&i.UpcomingEvents,
		&i.ContentLanguage,
		&i.PostingFrequency,
		&i.Niche,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBrandSettings = `-- name: UpsertBrandSettings :one
INSERT INTO brand_settings (
    instagram_account_id,
    content_goal, tone_traits, tone_custom_note,
    mix_useful, mix_selling, mix_personal, mix_entertaining,
    format_reels_enabled, format_reels_pct,
    format_carousel_enabled, format_carousel_pct,
    format_photo_enabled, format_photo_pct,
    banned_topics, banned_words, competitor_names, content_restrictions, custom_rules,
    products_services, target_audience, usp, team_members,
    location_address, working_hours, upcoming_events,
    content_language, posting_frequency, niche
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28, $29
)
ON CONFLICT (instagram_account_id) DO UPDATE SET
    content_goal = EXCLUDED.content_goal,
    tone_traits = EXCLUDED.tone_traits,
    tone_custom_note = EXCLUDED.tone_custom_note,
    mix_useful = EXCLUDED.mix_useful,
    mix_selling = EXCLUDED.mix_selling,
    mix_personal = EXCLUDED.mix_personal,
    mix_entertaining = EXCLUDED.mix_entertaining,
    format_reels_enabled = EXCLUDED.format_reels_enabled,
    format_reels_pct = EXCLUDED.format_reels_pct,
    format_carousel_enabled = EXCLUDED.format_carousel_enabled,
    format_carousel_pct = EXCLUDED.format_carousel_pct,
    format_photo_enabled = EXCLUDED.format_photo_enabled,
    format_photo_pct = EXCLUDED.format_photo_pct,
    banned_topics = EXCLUDED.banned_topics,
    banned_words = EXCLUDED.banned_words,
    competitor_names = EXCLUDED.competitor_names,
    content_restrictions = EXCLUDED.content_restrictions,
    custom_rules = EXCLUDED.custom_rules,
    products_services = EXCLUDED.products_services,
    target_audience = EXCLUDED.target_audience,
    usp = EXCLUDED.usp,
    team_members = EXCLUDED.team_members,
    location_address = EXCLUDED.location_address,
    working_hours = EXCLUDED.working_hours,
    upcoming_events = EXCLUDED.upcoming_events,
    content_language = EXCLUDED.content_language,
    posting_frequency = EXCLUDED.posting_frequency,
    niche = EXCLUDED.niche,
    updated_at = NOW()
RETURNING id, instagram_account_id, content_goal, tone_traits, tone_custom_note, mix_useful, mix_selling, mix_personal, mix_entertaining, format_reels_enabled, format_reels_pct, format_carousel_enabled, format_carousel_pct, format_photo_enabled, format_photo_pct, banned_topics, banned_words, competitor_names, content_restrictions, custom_rules, products_services, target_audience, usp, team_members, location_address, working_hours, upcoming_events, content_language, posting_frequency, niche, created_at, updated_at
`

type UpsertBrandSettingsParams struct {
	InstagramAccountID    uuid.UUID `json:"instagram_account_id"`
	ContentGoal           string    `json:"content_goal"`
	ToneTraits            []string  `json:"tone_traits"`
	ToneCustomNote        *string   `json:"tone_custom_note"`
	MixUseful             int32     `json:"mix_useful"`
	MixSelling            int32     `json:"mix_selling"`
	MixPersonal           int32     `json:"mix_personal"`
	MixEntertaining       int32     `json:"mix_entertaining"`
	FormatReelsEnabled    bool      `json:"format_reels_enabled"`
	FormatReelsPct        int32     `json:"format_reels_pct"`
	FormatCarouselEnabled bool      `json:"format_carousel_enabled"`
	FormatCarouselPct     int32     `json:"format_carousel_pct"`
	FormatPhotoEnabled    bool      `json:"format_photo_enabled"`
	FormatPhotoPct        int32     `json:"format_photo_pct"`
	BannedTopics          []string  `json:"banned_topics"`
	BannedWords           []string  `json:"banned_words"`
	CompetitorNames       []string  `json:"competitor_names"`
	ContentRestrictions   []string  `json:"content_restrictions"`
	CustomRules           *string   `json:"custom_rules"`
	ProductsServices      *string   `json:"products_services"`
	TargetAudience        *string   `json:"target_audience"`
	Usp                   *string   `json:"usp"`
	TeamMembers           []byte    `json:"team_members"`
	LocationAddress       *string   `json:"location_address"`
	WorkingHours          *string   `json:"working_hours"`
	UpcomingEvents        []byte    `json:"upcoming_events"`
	ContentLanguage       string    `json:"content_language"`
	PostingFrequency      string    `json:"posting_frequency"`
	Niche                 *string   `json:"niche"`
}

func (q *Queries) UpsertBrandSettings(ctx context.Context, arg UpsertBrandSettingsParams) (BrandSetting, error) {
	row := q.db.QueryRow(ctx, upsertBrandSettings,
		arg.InstagramAccountID,
		arg.ContentGoal,
		arg.ToneTraits,
		arg.ToneCustomNote,
		arg.MixUseful,
		arg.MixSelling,
		arg.MixPersonal,
		arg.MixEntertaining,
		arg.FormatReelsEnabled,
		arg.FormatReelsPct,
		arg.FormatCarouselEnabled,
		arg.FormatCarouselPct,
		arg.FormatPhotoEnabled,
		arg.FormatPhotoPct,
		arg.BannedTopics,
		arg.BannedWords,
		arg.CompetitorNames,
		arg.ContentRestrictions,
		arg.CustomRules,
		arg.ProductsServices,
		arg.TargetAudience,
		arg.Usp,
		arg.TeamMembers,
		arg.LocationAddress,
		arg.WorkingHours,
		arg.UpcomingEvents,
		arg.ContentLanguage,
		arg.PostingFrequency,
		arg.Niche,
	)
	var i BrandSetting
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.ContentGoal,
		&i.ToneTraits,
		&i.ToneCustomNote,
		&i.MixUseful,
		&i.MixSelling,
		&i.MixPersonal,
		&i.MixEntertaining,
		&i.FormatReelsEnabled,
		&i.FormatReelsPct,
		&i.FormatCarouselEnabled,
		&i.FormatCarouselPct,
		&i.FormatPhotoEnabled,
		&i.FormatPhotoPct,
		&i.BannedTopics,
		&i.BannedWords,
		&i.CompetitorNames,
		&i.ContentRestrictions,
		&i.CustomRules,
		&i.ProductsServices,
		&i.TargetAudience,
		&i.Usp,
		&i.TeamMembers,
		&i.LocationAddress,
		&i.WorkingHours,
		&i.UpcomingEvents,
		&i.ContentLanguage,
		&i.PostingFrequency,
		&i.Niche,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
