// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, provider, external_id, amount_cents, currency, status, plan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, provider, external_id, amount_cents, currency, status, plan, current_period_start, current_period_end, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Provider    string    `json:"provider"`
	ExternalID  string    `json:"external_id"`
	AmountCents int32     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Plan        string    `json:"plan"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.Plan,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, provider, external_id, amount_cents, currency, status, plan, current_period_start, current_period_end, created_at, updated_at FROM payments
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscription(ctx context.Context, userID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, userID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByExternalID = `-- name: GetPaymentByExternalID :one
SELECT id, user_id, provider, external_id, amount_cents, currency, status, plan, current_period_start, current_period_end, created_at, updated_at FROM payments WHERE provider = $1 AND external_id = $2
`

type GetPaymentByExternalIDParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetPaymentByExternalID(ctx context.Context, arg GetPaymentByExternalIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByExternalID, arg.Provider, arg.ExternalID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET
    status = $2,
    current_period_start = $3,
    current_period_end = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID                 uuid.UUID  `json:"id"`
	Status             string     `json:"status"`
	CurrentPeriodStart *time.Time `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time `json:"current_period_end"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}
