// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO content_plans (instagram_account_id, title, start_date, end_date, total_slots)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token
`

type CreatePlanParams struct {
	InstagramAccountID uuid.UUID `json:"instagram_account_id"`
	Title              string    `json:"title"`
	StartDate          time.Time `json:"start_date"`
	EndDate            time.Time `json:"end_date"`
	TotalSlots         int32     `json:"total_slots"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.InstagramAccountID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.TotalSlots,
	)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM content_plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token FROM content_plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const getPlanByShareToken = `-- name: GetPlanByShareToken :one
SELECT id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token FROM content_plans WHERE share_token = $1
`

func (q *Queries) GetPlanByShareToken(ctx context.Context, shareToken *string) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByShareToken, shareToken)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const getPlansByAccountID = `-- name: GetPlansByAccountID :many
SELECT id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token FROM content_plans
WHERE instagram_account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPlansByAccountID(ctx context.Context, instagramAccountID uuid.UUID) ([]ContentPlan, error) {
	rows, err := q.db.Query(ctx, getPlansByAccountID, instagramAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentPlan{}
	for rows.Next() {
		var i ContentPlan
		if err := rows.Scan(
			&i.ID,
			&i.InstagramAccountID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.TotalSlots,
			&i.ApprovedSlots,
			&i.PublishedSlots,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlanShareToken = `-- name: RevokePlanShareToken :exec
UPDATE content_plans SET share_token = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokePlanShareToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokePlanShareToken, id)
	return err
}

const setPlanShareToken = `-- name: SetPlanShareToken :one
UPDATE content_plans SET share_token = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token
`

type SetPlanShareTokenParams struct {
	ID         uuid.UUID `json:"id"`
	ShareToken *string   `json:"share_token"`
}

func (q *Queries) SetPlanShareToken(ctx context.Context, arg SetPlanShareTokenParams) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, setPlanShareToken, arg.ID, arg.ShareToken)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const updatePlanCounters = `-- name: UpdatePlanCounters :exec
UPDATE content_plans SET
    approved_slots = (SELECT COUNT(*) FROM content_slots cs WHERE cs.plan_id = $1 AND cs.status IN ('approved', 'queued', 'publishing', 'published')),
    published_slots = (SELECT COUNT(*) FROM content_slots cs WHERE cs.plan_id = $1 AND cs.status = 'published'),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePlanCounters(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePlanCounters, planID)
	return err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :one
UPDATE content_plans SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at, share_token
`

type UpdatePlanStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, updatePlanStatus, arg.ID, arg.Status)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}
