// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scraped_posts.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getScrapedPosts = `-- name: GetScrapedPosts :many
SELECT id, instagram_account_id, ig_post_id, post_type, caption, hashtags, likes_count, comments_count, posted_at, thumbnail_url, scraped_at FROM scraped_posts
WHERE instagram_account_id = $1
ORDER BY posted_at DESC
LIMIT $2
`

type GetScrapedPostsParams struct {
	InstagramAccountID uuid.UUID `json:"instagram_account_id"`
	Limit              int32     `json:"limit"`
}

func (q *Queries) GetScrapedPosts(ctx context.Context, arg GetScrapedPostsParams) ([]ScrapedPost, error) {
	rows, err := q.db.Query(ctx, getScrapedPosts, arg.InstagramAccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapedPost{}
	for rows.Next() {
		var i ScrapedPost
		if err := rows.Scan(
			&i.ID,
			&i.InstagramAccountID,
			&i.IgPostID,
			&i.PostType,
			&i.Caption,
			&i.Hashtags,
			&i.LikesCount,
			&i.CommentsCount,
			&i.PostedAt,
			&i.ThumbnailUrl,
			&i.ScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScrapedPost = `-- name: UpsertScrapedPost :exec
INSERT INTO scraped_posts (
    instagram_account_id, ig_post_id, post_type,
    caption, hashtags, likes_count, comments_count,
    posted_at, thumbnail_url
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (instagram_account_id, ig_post_id) DO UPDATE SET
    caption = EXCLUDED.caption,
    hashtags = EXCLUDED.hashtags,
    likes_count = EXCLUDED.likes_count,
    comments_count = EXCLUDED.comments_count,
    scraped_at = NOW()
`

type UpsertScrapedPostParams struct {
	InstagramAccountID uuid.UUID  `json:"instagram_account_id"`
	IgPostID           string     `json:"ig_post_id"`
	PostType           *string    `json:"post_type"`
	Caption            *string    `json:"caption"`
	Hashtags           []string   `json:"hashtags"`
	LikesCount         *int32     `json:"likes_count"`
	CommentsCount      *int32     `json:"comments_count"`
	PostedAt           *time.Time `json:"posted_at"`
	ThumbnailUrl       *string    `json:"thumbnail_url"`
}

func (q *Queries) UpsertScrapedPost(ctx context.Context, arg UpsertScrapedPostParams) error {
	_, err := q.db.Exec(ctx, upsertScrapedPost,
		arg.InstagramAccountID,
		arg.IgPostID,
		arg.PostType,
		arg.Caption,
		arg.Hashtags,
		arg.LikesCount,
		arg.CommentsCount,
		arg.PostedAt,
		arg.ThumbnailUrl,
	)
	return err
}
