// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slots.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveAllDraftSlots = `-- name: ApproveAllDraftSlots :execrows
UPDATE content_slots SET status = 'approved', updated_at = NOW()
WHERE plan_id = $1 AND status = 'draft' AND media::text != '[]'
`

func (q *Queries) ApproveAllDraftSlots(ctx context.Context, planID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, approveAllDraftSlots, planID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countApprovedWithoutMedia = `-- name: CountApprovedWithoutMedia :one
SELECT COUNT(*)::int FROM content_slots
WHERE plan_id = $1 AND status = 'approved' AND media::text = '[]'
`

func (q *Queries) CountApprovedWithoutMedia(ctx context.Context, planID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countApprovedWithoutMedia, planID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSlotsByPlanID = `-- name: CountSlotsByPlanID :one
SELECT COUNT(*)::int FROM content_slots WHERE plan_id = $1
`

func (q *Queries) CountSlotsByPlanID(ctx context.Context, planID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSlotsByPlanID, planID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSlot = `-- name: CreateSlot :one
INSERT INTO content_slots (
    plan_id, day_number, scheduled_date, scheduled_time,
    title, content_type, format, brief, caption, hashtags, cta
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, plan_id, day_number, scheduled_date, scheduled_time, title, content_type, format, brief, caption, hashtags, cta, media, status, is_user_content, published_at, ig_post_id, ig_post_url, error_message, retry_count, regeneration_count, created_at, updated_at
`

type CreateSlotParams struct {
	PlanID        uuid.UUID       `json:"plan_id"`
	DayNumber     int32           `json:"day_number"`
	ScheduledDate time.Time       `json:"scheduled_date"`
	ScheduledTime time.Time       `json:"scheduled_time"`
	Title         string          `json:"title"`
	ContentType   string          `json:"content_type"`
	Format        string          `json:"format"`
	Brief         json.RawMessage `json:"brief"`
	Caption       string          `json:"caption"`
	Hashtags      []string        `json:"hashtags"`
	Cta           *string         `json:"cta"`
}

func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (ContentSlot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.PlanID,
		arg.DayNumber,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.Title,
		arg.ContentType,
		arg.Format,
		arg.Brief,
		arg.Caption,
		arg.Hashtags,
		arg.Cta,
	)
	var i ContentSlot
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.Title,
		&i.ContentType,
		&i.Format,
		&i.Brief,
		&i.Caption,
		&i.Hashtags,
		&i.Cta,
		&i.Media,
		&i.Status,
		&i.IsUserContent,
		&i.PublishedAt,
		&i.IgPostID,
		&i.IgPostUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.RegenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlotByID = `-- name: GetSlotByID :one
SELECT id, plan_id, day_number, scheduled_date, scheduled_time, title, content_type, format, brief, caption, hashtags, cta, media, status, is_user_content, published_at, ig_post_id, ig_post_url, error_message, retry_count, regeneration_count, created_at, updated_at FROM content_slots WHERE id = $1
`

func (q *Queries) GetSlotByID(ctx context.Context, id uuid.UUID) (ContentSlot, error) {
	row := q.db.QueryRow(ctx, getSlotByID, id)
	var i ContentSlot
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.Title,
		&i.ContentType,
		&i.Format,
		&i.Brief,
		&i.Caption,
		&i.Hashtags,
		&i.Cta,
		&i.Media,
		&i.Status,
		&i.IsUserContent,
		&i.PublishedAt,
		&i.IgPostID,
		&i.IgPostUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.RegenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlotsByPlanID = `-- name: GetSlotsByPlanID :many
SELECT id, plan_id, day_number, scheduled_date, scheduled_time, title, content_type, format, brief, caption, hashtags, cta, media, status, is_user_content, published_at, ig_post_id, ig_post_url, error_message, retry_count, regeneration_count, created_at, updated_at FROM content_slots WHERE plan_id = $1 ORDER BY day_number
`

func (q *Queries) GetSlotsByPlanID(ctx context.Context, planID uuid.UUID) ([]ContentSlot, error) {
	rows, err := q.db.Query(ctx, getSlotsByPlanID, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentSlot{}
	for rows.Next() {
		var i ContentSlot
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.DayNumber,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.Title,
			&i.ContentType,
			&i.Format,
			&i.Brief,
			&i.Caption,
			&i.Hashtags,
			&i.Cta,
			&i.Media,
			&i.Status,
			&i.IsUserContent,
			&i.PublishedAt,
			&i.IgPostID,
			&i.IgPostUrl,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.RegenerationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlotsReadyToPublish = `-- name: GetSlotsReadyToPublish :many
SELECT cs.id, cs.plan_id, cs.day_number, cs.scheduled_date, cs.scheduled_time, cs.title, cs.content_type, cs.format, cs.brief, cs.caption, cs.hashtags, cs.cta, cs.media, cs.status, cs.is_user_content, cs.published_at, cs.ig_post_id, cs.ig_post_url, cs.error_message, cs.retry_count, cs.regeneration_count, cs.created_at, cs.updated_at, cp.instagram_account_id
FROM content_slots cs
JOIN content_plans cp ON cs.plan_id = cp.id
WHERE cs.status = 'approved'
  AND cs.scheduled_date = CURRENT_DATE
  AND cs.scheduled_time <= CURRENT_TIME
  AND cs.media::text != '[]'
ORDER BY cs.scheduled_time
`

type GetSlotsReadyToPublishRow struct {
	ID                 uuid.UUID       `json:"id"`
	PlanID             uuid.UUID       `json:"plan_id"`
	DayNumber          int32           `json:"day_number"`
	ScheduledDate      time.Time       `json:"scheduled_date"`
	ScheduledTime      time.Time       `json:"scheduled_time"`
	Title              string          `json:"title"`
	ContentType        string          `json:"content_type"`
	Format             string          `json:"format"`
	Brief              json.RawMessage `json:"brief"`
	Caption            string          `json:"caption"`
	Hashtags           []string        `json:"hashtags"`
	Cta                *string         `json:"cta"`
	Media              json.RawMessage `json:"media"`
	Status             string          `json:"status"`
	IsUserContent      bool            `json:"is_user_content"`
	PublishedAt        *time.Time      `json:"published_at"`
	IgPostID           *string         `json:"ig_post_id"`
	IgPostUrl          *string         `json:"ig_post_url"`
	ErrorMessage       *string         `json:"error_message"`
	RetryCount         int32           `json:"retry_count"`
	RegenerationCount  int32           `json:"regeneration_count"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	InstagramAccountID uuid.UUID       `json:"instagram_account_id"`
}

func (q *Queries) GetSlotsReadyToPublish(ctx context.Context) ([]GetSlotsReadyToPublishRow, error) {
	rows, err := q.db.Query(ctx, getSlotsReadyToPublish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSlotsReadyToPublishRow{}
	for rows.Next() {
		var i GetSlotsReadyToPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.DayNumber,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.Title,
			&i.ContentType,
			&i.Format,
			&i.Brief,
			&i.Caption,
			&i.Hashtags,
			&i.Cta,
			&i.Media,
			&i.Status,
			&i.IsUserContent,
			&i.PublishedAt,
			&i.IgPostID,
			&i.IgPostUrl,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.RegenerationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstagramAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSlotRegeneration = `-- name: IncrementSlotRegeneration :exec
UPDATE content_slots SET
    regeneration_count = regeneration_count + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementSlotRegeneration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementSlotRegeneration, id)
	return err
}

const incrementSlotRetry = `-- name: IncrementSlotRetry :exec
UPDATE content_slots SET
    retry_count = retry_count + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementSlotRetry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementSlotRetry, id)
	return err
}

const queueApprovedSlots = `-- name: QueueApprovedSlots :execrows
UPDATE content_slots SET status = 'queued', updated_at = NOW()
WHERE plan_id = $1 AND status = 'approved' AND media::text != '[]'
`

func (q *Queries) QueueApprovedSlots(ctx context.Context, planID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, queueApprovedSlots, planID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipSlotsMissingMedia = `-- name: SkipSlotsMissingMedia :execrows
UPDATE content_slots SET
  status = 'skipped',
  error_message = 'No media uploaded',
  updated_at = NOW()
WHERE status = 'approved'
  AND scheduled_date = CURRENT_DATE
  AND scheduled_time <= CURRENT_TIME
  AND media::text = '[]'
`

func (q *Queries) SkipSlotsMissingMedia(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, skipSlotsMissingMedia)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSlot = `-- name: UpdateSlot :one
UPDATE content_slots SET
    caption = COALESCE($2, caption),
    hashtags = COALESCE($3, hashtags),
    scheduled_time = COALESCE($4, scheduled_time),
    scheduled_date = COALESCE($5, scheduled_date),
    status = COALESCE($6, status),
    is_user_content = COALESCE($7, is_user_content),
    updated_at = NOW()
WHERE id = $1
RETURNING id, plan_id, day_number, scheduled_date, scheduled_time, title, content_type, format, brief, caption, hashtags, cta, media, status, is_user_content, published_at, ig_post_id, ig_post_url, error_message, retry_count, regeneration_count, created_at, updated_at
`

type UpdateSlotParams struct {
	ID            uuid.UUID   `json:"id"`
	Caption       *string     `json:"caption"`
	Hashtags      []string    `json:"hashtags"`
	ScheduledTime pgtype.Time `json:"scheduled_time"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
	Status        *string     `json:"status"`
	IsUserContent pgtype.Bool `json:"is_user_content"`
}

func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) (ContentSlot, error) {
	row := q.db.QueryRow(ctx, updateSlot,
		arg.ID,
		arg.Caption,
		arg.Hashtags,
		arg.ScheduledTime,
		arg.ScheduledDate,
		arg.Status,
		arg.IsUserContent,
	)
	var i ContentSlot
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.Title,
		&i.ContentType,
		&i.Format,
		&i.Brief,
		&i.Caption,
		&i.Hashtags,
		&i.Cta,
		&i.Media,
		&i.Status,
		&i.IsUserContent,
		&i.PublishedAt,
		&i.IgPostID,
		&i.IgPostUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.RegenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSlotMedia = `-- name: UpdateSlotMedia :one
UPDATE content_slots SET media = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, plan_id, day_number, scheduled_date, scheduled_time, title, content_type, format, brief, caption, hashtags, cta, media, status, is_user_content, published_at, ig_post_id, ig_post_url, error_message, retry_count, regeneration_count, created_at, updated_at
`

type UpdateSlotMediaParams struct {
	ID    uuid.UUID       `json:"id"`
	Media json.RawMessage `json:"media"`
}

func (q *Queries) UpdateSlotMedia(ctx context.Context, arg UpdateSlotMediaParams) (ContentSlot, error) {
	row := q.db.QueryRow(ctx, updateSlotMedia, arg.ID, arg.Media)
	var i ContentSlot
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.Title,
		&i.ContentType,
		&i.Format,
		&i.Brief,
		&i.Caption,
		&i.Hashtags,
		&i.Cta,
		&i.Media,
		&i.Status,
		&i.IsUserContent,
		&i.PublishedAt,
		&i.IgPostID,
		&i.IgPostUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.RegenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSlotPublished = `-- name: UpdateSlotPublished :exec
UPDATE content_slots SET
    status = 'published',
    published_at = NOW(),
    ig_post_id = $2,
    ig_post_url = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSlotPublishedParams struct {
	ID        uuid.UUID `json:"id"`
	IgPostID  *string   `json:"ig_post_id"`
	IgPostUrl *string   `json:"ig_post_url"`
}

func (q *Queries) UpdateSlotPublished(ctx context.Context, arg UpdateSlotPublishedParams) error {
	_, err := q.db.Exec(ctx, updateSlotPublished, arg.ID, arg.IgPostID, arg.IgPostUrl)
	return err
}

const updateSlotStatus = `-- name: UpdateSlotStatus :exec
UPDATE content_slots SET
    status = $2,
    error_message = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSlotStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) UpdateSlotStatus(ctx context.Context, arg UpdateSlotStatusParams) error {
	_, err := q.db.Exec(ctx, updateSlotStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
