// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countAccountsByUserID = `-- name: CountAccountsByUserID :one
SELECT COUNT(*)::int FROM instagram_accounts WHERE user_id = $1
`

func (q *Queries) CountAccountsByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAccountsByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePlansByAccountID = `-- name: DeletePlansByAccountID :exec
DELETE FROM content_plans WHERE instagram_account_id = $1
`

func (q *Queries) DeletePlansByAccountID(ctx context.Context, instagramAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlansByAccountID, instagramAccountID)
	return err
}

const getActivePlanByAccountID = `-- name: GetActivePlanByAccountID :one
SELECT id, instagram_account_id, title, start_date, end_date, status, total_slots, approved_slots, published_slots, created_at, updated_at FROM content_plans
WHERE instagram_account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActivePlanByAccountID(ctx context.Context, instagramAccountID uuid.UUID) (ContentPlan, error) {
	row := q.db.QueryRow(ctx, getActivePlanByAccountID, instagramAccountID)
	var i ContentPlan
	err := row.Scan(
		&i.ID,
		&i.InstagramAccountID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TotalSlots,
		&i.ApprovedSlots,
		&i.PublishedSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyUsage = `-- name: GetMonthlyUsage :one
SELECT COALESCE(
    (SELECT used_count FROM usage_tracking
     WHERE user_id = $1
       AND action = $2
       AND period_start = date_trunc('month', CURRENT_DATE)::date),
    0
)::int AS used_count
`

type GetMonthlyUsageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Action string    `json:"action"`
}

func (q *Queries) GetMonthlyUsage(ctx context.Context, arg GetMonthlyUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMonthlyUsage, arg.UserID, arg.Action)
	var used_count int32
	err := row.Scan(&used_count)
	return used_count, err
}

const getUserPlan = `-- name: GetUserPlan :one
SELECT plan FROM users WHERE id = $1
`

func (q *Queries) GetUserPlan(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPlan, id)
	var plan string
	err := row.Scan(&plan)
	return plan, err
}

const incrementUsage = `-- name: IncrementUsage :exec
INSERT INTO usage_tracking (user_id, action, period_start, period_end, used_count)
VALUES (
    $1, $2,
    date_trunc('month', CURRENT_DATE)::date,
    (date_trunc('month', CURRENT_DATE) + INTERVAL '1 month' - INTERVAL '1 day')::date,
    1
)
ON CONFLICT (user_id, action, period_start)
DO UPDATE SET
    used_count = usage_tracking.used_count + 1,
    updated_at = NOW()
`

type IncrementUsageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Action string    `json:"action"`
}

func (q *Queries) IncrementUsage(ctx context.Context, arg IncrementUsageParams) error {
	_, err := q.db.Exec(ctx, incrementUsage, arg.UserID, arg.Action)
	return err
}
