// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, supabase_user_id, email, plan, plan_expires_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SupabaseUserID,
		&i.Email,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySupabaseID = `-- name: GetUserBySupabaseID :one
SELECT id, supabase_user_id, email, plan, plan_expires_at, created_at, updated_at FROM users WHERE supabase_user_id = $1
`

func (q *Queries) GetUserBySupabaseID(ctx context.Context, supabaseUserID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySupabaseID, supabaseUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SupabaseUserID,
		&i.Email,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users SET
    plan = $2,
    plan_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, supabase_user_id, email, plan, plan_expires_at, created_at, updated_at
`

type UpdateUserPlanParams struct {
	ID            uuid.UUID  `json:"id"`
	Plan          string     `json:"plan"`
	PlanExpiresAt *time.Time `json:"plan_expires_at"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPlan, arg.ID, arg.Plan, arg.PlanExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SupabaseUserID,
		&i.Email,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (supabase_user_id, email)
VALUES ($1, $2)
ON CONFLICT (supabase_user_id) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = NOW()
RETURNING id, supabase_user_id, email, plan, plan_expires_at, created_at, updated_at
`

type UpsertUserParams struct {
	SupabaseUserID uuid.UUID `json:"supabase_user_id"`
	Email          string    `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.SupabaseUserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SupabaseUserID,
		&i.Email,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
